In [3]:
import os
import pandas as pd

In [4]:
root = os.path.dirname(os.path.abspath(os.getcwd()))

In [6]:
data = pd.read_csv(os.path.join(root, "data","train","train.csv"), lineterminator='\n', index_col=0)

In [9]:
data

,id,title,original_language,overview,release_date,adult,poster_path,Action,Adventure,Animation,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,19173,Diary of a Nymphomaniac,es,A chronicle of the life of a middle-class Fren...,2008-10-17,False,yVYTeiFv7oQsSQF9OBRngg7ZqLg.jpg,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1029446,Selina's Gold,tl,Selina's father sells her to Tiago who makes h...,2022-10-28,False,4a0X2GKDmhhp1U2FUKtKY6uNQHL.jpg,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,15417,Every Which Way but Loose,en,"Philo Beddoe is your regular, easygoing, truck...",1978-12-16,False,b97csw2kCtXwqJpz7B5jFIS6eFy.jpg,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,57718,Megamind: The Button of Doom,en,For their first day on the job as the new prot...,2011-02-25,False,3uKLJ8x5fgggTH4BGGwuUNuf8h0.jpg,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,420707,Cage Dive,en,Three friends from California are filming an a...,2017-08-11,False,3uUO9eDxHeDREIX77BaQiI88ajp.jpg,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7786,263115,Logan,en,"In the near future, a weary Logan cares for an...",2017-02-28,False,fnbjcRDYn6YviCcePDnGdyAkYsB.jpg,1,0,0,...,0,0,0,0,0,0,0,0,0,0
7787,484907,Homebound,en,A young woman arrives at the home of her new h...,2022-04-01,False,8ceAveKWI7PoYGGOFz2WW7xjtYF.jpg,0,0,0,...,0,1,0,0,0,0,0,0,0,0
7788,16931,Into the Blue 2: The Reef,en,When they're hired to recover the lost treasur...,2009-04-21,False,jb0KPSNWMyDeSpZ6lRk030kV5W0.jpg,1,0,0,...,0,0,0,0,0,0,0,0,0,0
7789,9469,He Got Game,en,A basketball player's father must try to convi...,1998-05-01,False,kd8hRaysUQOz7AvSorZDJHuihcJ.jpg,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7790,631132,Goblin Slayer: Goblin's Crown,ja,Goblin Slayer and his party head up to the sno...,2020-02-01,False,oyDaF4za9C9GxfYSyZUmj2aZGJT.jpg,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [25]:
data[data["poster_path"] == "lQlsFvRl0Qy1FSGl6yVpT2fLIsA.jpg"]

,id,title,original_language,overview,release_date,adult,poster_path,Action,Adventure,Animation,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
2866,663,Saw IV,en,Jigsaw and his apprentice Amanda are dead. Now...,2007-10-25,False,lQlsFvRl0Qy1FSGl6yVpT2fLIsA.jpg,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [23]:
def contains_jpg(x):
    if ".jpg" in x:
        f = os.path.isfile(f"{root}/images/raw/{x}")
        if not f:
            print(x)

In [24]:
data["poster_path"].apply(lambda x: contains_jpg(x))

0       None
1       None
2       None
3       None
4       None
        ...
7786    None
7787    None
7788    None
7789    None
7790    None
Name: poster_path, Length: 7791, dtype: object